### ISSUE TITLE
downgrade release feedback

### ISSUE THREAD

**Issue by staabm** [symplify/phpstan-rules#108]
https://github.com/symplify/phpstan-rules/blob/5769d2a231c414756495501a3b0c87b9299e8c85/.github/workflows/downgraded_release.yaml#L16-L18

it looks like the downgrade job will checkout whatever revision is the latest one at the time of running the job.
this means if someone commits right after a tag, a commit might slip into the downgraded release which was not part of the non-downgraded one

same problem when e.g. github actions are slow or down and the actions runs a bit later as the actual tag happens

-----

https://github.com/symplify/phpstan-rules/blob/5769d2a231c414756495501a3b0c87b9299e8c85/.github/workflows/downgraded_release.yaml#L62-L64

overwriting a existing git tag should be prevented at all costs.
most systems which learned about the previous git tag will likely not update to the newer re-tagged version.
that means some consumers will "randomly" get the downgraded version and some will get the latest version, depending on how they fetch the tags.

**Comment by TomasVotruba** [comment]
Hi, thanks for feedback. I agree with you.
If you find a way to improve this, PR is welcomed 👍
