### ISSUE TITLE
Composer: update nikic/php-parser

### ISSUE THREAD

**Issue by dada-amater** [symplify/phpstan-rules#112]
Hello Tomas,

thank you for your great package, we like it very much. Can you please unlock the `nikic/php-parser 5` dependency? It is required by phpunit 11.

Thank you very much for your great work.

**Comment by dada-amater** [comment]
It was resolved in https://github.com/symplify/phpstan-rules/pull/111, just there is no release.

**Comment by TomasVotruba** [comment]
It was updated and released correctly, just the build `composer.json` is different and need to  be updated too:
https://github.com/symplify/phpstan-rules/blob/main/build/target-repository/composer.json

**Comment by TomasVotruba** [comment]
Resolved in https://github.com/symplify/phpstan-rules/commit/ab872b8a1c451be9547f6c29708d591bb0edbf78
