### ISSUE TITLE
NoMixed rules where super useful

### ISSUE THREAD

**Issue by dereuromark** [symplify/phpstan-rules#138]
I am a bit sad that the only things we used:

rules:
    - Symplify\PHPStanRules\Rules\Explicit\NoMixedPropertyFetcherRule
    - Symplify\PHPStanRules\Rules\Explicit\NoMixedMethodCallerRule
    
Are both removed in v13 forward

You might not have used them much, but others might have.
Is there any way those could be supported as ext package maybe? Like phpstan-rules-ext as opt-in?
This way we could continue using them without having to maintain PHPStan rulesets ourselves.

They are superuseful in showing where methods, variables and properties are not clear and thus the following code not properly PHPStan asserted, since with mixed it will just be silent.

**Comment by TomasVotruba** [comment]
Don't worry, they're still here :) just in a smaller decopuled package with improved functionality

See https://github.com/symplify/phpstan-rules/pull/128
And https://getrector.com/blog/introducing-type-perfect-for-extra-safety

**Comment by TomasVotruba** [comment]
Make sure you're subscribed to release notes here, so you won't miss important info
https://github.com/symplify/phpstan-rules/releases

**Comment by dereuromark** [comment]
Something is still weird, though

Before, I could silence them using (with new names)

    #- Rector\TypePerfect\Rules\NoMixedPropertyFetcherRule
    #- Rector\TypePerfect\Rules\NoMixedMethodCallerRule

This is now not possible anymore with the new way. They are always active by default.

**Comment by TomasVotruba** [comment]
Check the README: https://github.com/rectorphp/type-perfect/?tab=readme-ov-file#configure
