### ISSUE TITLE
Rules are incompatible with PHPStan 2.0

### ISSUE THREAD

**Issue by kamil-tekiela** [symplify/phpstan-rules#143]
I have found that when I run PHPStan I get:

> Service of type Symplify\PHPStanRules\NodeAnalyzer\IfResemblingMatchAnalyzer: Service of type PhpParser\PrettyPrinter\Standard required by $printerStandard in IfResemblingMatchAnalyzer::__construct() not found. Did you add it to configuration file?

**Comment by ThomasLandauer** [comment]
Upgrade guide: https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md#upgrading-guide-for-extension-developers

**Comment by staabm** [comment]
fixed in the latest release

**Comment by TomasVotruba** [comment]
Thank you :pray:
