### ISSUE TITLE
`ForbiddenThisArgumentRule` is overly strict on native function calls

### ISSUE THREAD

**Issue by keulinho** [symplify/phpstan-rules#15]
The `ForbiddenThisArgumentRule` prevents passing `$this` as argument to a method call, which is actually a pretty nice rule.

However IMHO calls to native functions should included from that rule, as there is no way to refactor those. In the current implementation there is already a exception for `method_exists` function call: https://github.com/symplify/phpstan-rules/blob/main/src/Rules/ForbiddenThisArgumentRule.php#L121

But there are more function calls like this where it is IMHO totally valid or even needed to pass `$this` into e.g.: `is_a`, `is_subclass_of`, `get_object_vars`, `get_class_methods` and probably more i didn't thought of now. IMHO the rule should skip all function calls.

What do you think? Happy to prepare a PR if it will be accepted in general

**Comment by TomasVotruba** [comment]
> What do you think? Happy to prepare a PR if it will be accepted in general


Makes sense, go for it :+1:
