### ISSUE TITLE
should CheckTypehintCallerTypeRuleTest skip methods which are annotated `@api`?

### ISSUE THREAD

**Issue by staabm** [symplify/phpstan-rules#20]
a `@api` method doesn't necessarily has all its callers within the current project, therefore we cannot judge about it, tight?

**Comment by TomasVotruba** [comment]
Seems valid. What is your exact use case you've came across this?

**Comment by TomasVotruba** [comment]
I see, let's go for it :+1:

**Comment by staabm** [comment]
I realized that all non-private methods are skipped. so my use-case is already covered:

https://github.com/symplify/phpstan-rules/blob/bd0dc55555494c84c37e0e05b554836c6839c519/src/NodeFinder/ClassMethodNodeFinder.php#L46-L48
