### ISSUE TITLE
[Feature request] Check if certain option is set on each form

### ISSUE THREAD

**Issue by ThomasLandauer** [symplify/phpstan-rules#34]
I'd like to check if the option `csrf_protection` is set on each form explicitly, to make sure I haven't forgot one.
Ondřej Mirtes says it's possible https://github.com/phpstan/phpstan-symfony/issues/343#issuecomment-1501111078 but I don't know how to implement such a rule.
With Symplify, the form options to look for could be configured as `arguments`.

P.S.: I know that form options can be configured globally, but I'd like to make sure that my forms work independently of global settings.

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion, but it's not the right fit here.

This rather seems like a custom rule for your rule set :+1:
