### ISSUE TITLE
ForbiddenInlineClassMethodRule and complex call

### ISSUE THREAD

**Issue by szymonmil** [symplify/phpstan-rules#37]
I think that there are several cases, when "only calling another method" has added value. Here are few examples, which are (in my opinion) valuable and should not be inlined:

Example 1: 
```php
private function generateSubscribtionLink(int $userId): string
{
    return $this->router->generate(
        'subscribe',
        [userId' => $userId, 'source' => SubscriptionSource::WEBSITE],
        UrlGeneratorInterface::ABSOLUTE_URL
    );
}
```
Example 2: 
```php
private function getUser(int $userId): User
{
    return $this->manager
        ->getRepository(User::class)
        ->createQueryBuilder('user')
        ->where('user.id = :userId')
        ->setParameter('userId', $userId)
        ->getQuery()
        ->getResult();
}
```

That approach is increasing readability and cleanliness of code. (Of course in some cases you should create new class with functionality provided by that complex method, but my approach is better than inlining it in more complex function).

So i suggest, to change that rule that it won't throw error if method "only" calling another method built by more than one line. Of course I can write my examples in one line, but it's violence of other rules.

**Comment by szymonm01** [comment]
> 

Ok, I will try to implement that

**Comment by szymonmil** [comment]
Merged
