### ISSUE TITLE
Using PSR-20 (Clock) instead of "new DataTime"

### ISSUE THREAD

**Issue by szymonmil** [symplify/phpstan-rules#51]
Hi,
what do you think about adding rule which will disallow using `new DataTime()` or `new DateTimeImmutable()` in code, due to PSR-20.
Using DataTime without providing specific date (using it with default 'now'), can be (and should be) converted to Clock, for example for testing purposes.

**Comment by TomasVotruba** [comment]
Hi, I think this is better designed for a custom rule.
