### ISSUE TITLE
ExplicitClassPrefixSuffixRule Impossible to select subset of actions

### ISSUE THREAD

**Issue by sakarikl** [symplify/phpstan-rules#59]
With old implementation it was possible to select which of the 3 rules you wanted to run.

This commit https://github.com/symplify/phpstan-rules/commit/c584728fa538b0bc9bb3582ca3bf45b9872b1dc4 combined existing three rules into one and we can no longer select which of them we want to run.

As a bonus it would be nice to be able to define if required term would need to be at the start of class name or at the end. Our naming convention is to have Abstract and Interface at the end of class name. But we used Trait rule of those previous implementations.

**Comment by TomasVotruba** [comment]
Hi, thanks for reaching out.

This naming conventions usually alling together, so we merged it to one to keep it simpler to use and maintain. In you case, it would be better to create a custom rule to handle prefix/suffix needs of your project.
