### ISSUE TITLE
Version number out of sync with packagist.org

### ISSUE THREAD

**Issue by ThomasLandauer** [symplify/phpstan-rules#92]
packagist.org shows that `12.3.1` is the current version, whereas here on GitHub the latest release is `11.1.0 `

**Comment by TomasVotruba** [comment]
I see the latest Github release is 12.3.1 - https://github.com/symplify/phpstan-rules/tags

**Comment by ThomasLandauer** [comment]
Thanks, I see. I was figuring that my problem at https://github.com/symplify/phpstan-rules/issues/93 is maybe related to some version discrepancy.

Anyway, I understand that writing release notes is cumbersome. But when raising to a next major version (e.g. 11 to 12), you should at least drop a line regarding the possible BC breaks (or what the "major" change is)
