### ISSUE TITLE
12.3.1 not working

### ISSUE THREAD

**Issue by ThomasLandauer** [symplify/phpstan-rules#93]
After upgrading from 11.4.1.72, PHPStan now gives me:

> In Resolver.php line 115:
> Service (Symplify\PHPStanRules\Rules\CheckAttributteArgumentClassExistsRule::__construct()): Class 'Symplify\PHPStanRules\Rules\CheckAttributteArgumentClassExistsRule' not found.

**Comment by TomasVotruba** [comment]
The message is pretty clear.
The `CheckAttributteArgumentClassExistsRule` does not exist. Remove it from config and re-run

**Comment by TomasVotruba** [comment]
The best and easiest way is to check recent PRs:
https://github.com/symplify/phpstan-rules/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed
